### PR TITLE
Fix Issue #24 - wso2-release-helper-plugin fails on Windows

### LINKED ISSUE #24: wso2-release-helper-plugin fails on Windows
**Description:**
wso2-release-helper-plugin fails on Windows because artifact.xml is renamed before output streams closed in the class **AbstractMavenReleaseMojo** method **updateArtifactVersions()**

On Linux, Java does not seems to be bothered if the file is renamed while the output stream still not closed, on Windows instead the file artifact.xml is deleted and the artifact.xml.tmp file is not renamed.

**Suggested Labels:**
artifact.xml, FileOutputStream

**Affected Product Version:**
all

**Steps to reproduce:**
run:

mvn release:clean release:prepare -DdryRun=true

On Linux you will have the artifact.next and artifact.tag files created. On Windows you will have only artifact.xml.tmp created.

**Sugested Fix**

Delete _artifact.xml_ and rename _artifact.xml.tmp_ file after ouput and input streams are closed, so instead of the following code:

        String artifactXmlPath = artifactXml.getPath();
        artifactXml.delete();
        artifactXmlTemp.renameTo(new File(artifactXmlPath));
        inputStream.close();
        xmlStreamReader.close();
        outputStream.close();
        xmlStreamWriter.flush();
        xmlStreamWriter.close();

just have this code:

        inputStream.close();
        xmlStreamReader.close();
        outputStream.close();
        xmlStreamWriter.flush();
        xmlStreamWriter.close();

        String artifactXmlPath = artifactXml.getPath();
        artifactXml.delete();
        artifactXmlTemp.renameTo(new File(artifactXmlPath));

### PR DESCRIPTION
**Pull request by Lotzy**
## Purpose
Fixes #24 from this link https://github.com/wso2/maven-tools/issues/24.

### CODE REVIEW

**Comment by kasunbg** [comment]
Fixes #24

**Comment by kasunbg** [comment]
@Lotzy approved the PR with thanks. Will wait to see feedback from others till tomorrow.

**Comment by Lotzy** [comment]
Thanks!

**Comment by Lotzy** [comment]
Hi there! Any news about this pull request?

**Comment by kasunbg** [comment]
The build/release is a success - https://wso2.org/jenkins/job/maven-tools/1742/

Thank you for your help to improve the codebase!

**Comment by Lotzy** [comment]
I thank you too, for the merge and release of the fix.
Best regards!

**Pull request merged**
